name: build-test

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - name: Check out project
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: |
          6.0.x
          5.0.x

    - name: Build project
      run: dotnet build src

    - name: Test project
      run: dotnet test src
